<?php

use App\Models\AlertRule;

return [
    'manifest' => 'database/market-packs/telecom.php',
    'key' => 'telecom',
    'name' => 'Telecom',
    'description' => 'Operational defaults for connectivity, operators, broadband, network infrastructure and telecom policy monitoring.',
    'market_category' => 'connectivity',
    'defaults' => ['locale' => 'en', 'recency_days' => 30],
    'sources' => [
        [
            'key' => 'telecom-demo-watchlist',
            'name' => 'Telecom demo watchlist',
            'source_type' => 'manual',
            'domain' => 'example.com',
            'authority_score' => 45,
            'discovery_config_json' => [
                'adapter' => 'manual',
                'fetch_priority_threshold' => 80,
                'urls' => [
                    ['url' => 'https://example.com/telecom/5g-rollout', 'priority' => 90, 'page_type' => 'article', 'title' => '5G rollout coverage'],
                ],
            ],
        ],
        [
            'key' => 'telecoms-news-rss',
            'name' => 'Telecoms news feed',
            'source_type' => 'rss',
            'base_url' => 'https://www.telecoms.com/feed',
            'domain' => 'telecoms.com',
            'trust_level' => 4,
            'authority_score' => 73,
            'discovery_config_json' => ['adapter' => 'rss', 'priority' => 75, 'max_urls' => 50],
        ],
        [
            'key' => 'fcc-news',
            'name' => 'FCC news',
            'source_type' => 'known_source_crawl',
            'base_url' => 'https://www.fcc.gov/news-events',
            'domain' => 'fcc.gov',
            'trust_level' => 5,
            'authority_score' => 84,
            'discovery_config_json' => ['adapter' => 'known_source_crawl', 'priority' => 80, 'max_urls' => 25],
        ],
    ],
    'competitors' => [
        ['key' => 'verizon', 'name' => 'Verizon', 'domain' => 'verizon.com'],
        ['key' => 'att', 'name' => 'AT&T', 'domain' => 'att.com', 'aliases' => ['AT and T']],
        ['key' => 't-mobile', 'name' => 'T-Mobile', 'domain' => 't-mobile.com', 'aliases' => ['T Mobile']],
        ['key' => 'vodafone', 'name' => 'Vodafone', 'domain' => 'vodafone.com'],
    ],
    'themes' => [
        ['key' => 'five_g_networks', 'name' => '5G networks', 'weight' => 1.2],
        ['key' => 'fiber_broadband', 'name' => 'Fiber broadband', 'weight' => 1.05],
        ['key' => 'network_reliability', 'name' => 'Network reliability', 'weight' => 1.15],
        ['key' => 'enterprise_connectivity', 'name' => 'Enterprise connectivity', 'weight' => 1.1],
    ],
    'keywords' => [
        ['theme' => 'five_g_networks', 'keyword' => '5G rollout', 'intent' => 'deployment', 'weight' => 1.2],
        ['theme' => 'five_g_networks', 'keyword' => 'private network', 'intent' => 'enterprise'],
        ['theme' => 'fiber_broadband', 'keyword' => 'fiber broadband', 'intent' => 'infrastructure'],
        ['theme' => 'network_reliability', 'keyword' => 'network outage', 'intent' => 'risk', 'weight' => 1.2],
        ['theme' => 'enterprise_connectivity', 'keyword' => 'IoT connectivity', 'intent' => 'enterprise'],
        ['theme' => 'enterprise_connectivity', 'keyword' => 'edge computing', 'intent' => 'technology'],
    ],
    'metrics' => [
        ['key' => 'source_authority', 'name' => 'Source authority', 'unit' => 'score', 'direction' => 'higher_is_better', 'weight' => 1.2],
        ['key' => 'topic_ownership', 'name' => 'Topic ownership', 'unit' => 'score', 'direction' => 'higher_is_better', 'weight' => 1.1],
        ['key' => 'geo_visibility', 'name' => 'GEO visibility', 'unit' => 'score', 'direction' => 'higher_is_better', 'weight' => 1.05],
    ],
    'alert_templates' => [
        ['key' => 'brand-page', 'name' => 'Telecom brand mention', 'trigger' => AlertRule::TRIGGER_NEW_BRAND_PAGE, 'severity' => 'medium', 'conditions' => ['market_pack' => 'telecom']],
        ['key' => 'geo-citation-gain', 'name' => 'Telecom GEO citation gain', 'trigger' => AlertRule::TRIGGER_GEO_CITATION_GAIN, 'severity' => 'medium', 'conditions' => ['market_pack' => 'telecom']],
        ['key' => 'serp-top-10-loss', 'name' => 'Telecom SERP top 10 loss', 'trigger' => AlertRule::TRIGGER_SERP_TOP_10_LOSS, 'severity' => 'high', 'conditions' => ['market_pack' => 'telecom']],
        ['key' => 'high-pr-value', 'name' => 'Telecom high PR value page', 'trigger' => AlertRule::TRIGGER_HIGH_PR_VALUE_PAGE, 'severity' => 'medium', 'conditions' => ['market_pack' => 'telecom', 'min_score' => 80]],
        ['key' => 'high-risk-negative', 'name' => 'Telecom high-risk negative page', 'trigger' => AlertRule::TRIGGER_HIGH_RISK_NEGATIVE_PAGE, 'severity' => 'high', 'conditions' => ['market_pack' => 'telecom', 'min_source_authority' => 72, 'max_compound_score' => -0.1]],
        ['key' => 'competitor-pressure-spike', 'name' => 'Telecom competitor pressure spike', 'trigger' => AlertRule::TRIGGER_COMPETITOR_PRESSURE_SPIKE, 'severity' => 'medium', 'conditions' => ['market_pack' => 'telecom', 'min_competitor_pressure' => 72, 'min_delta' => 12]],
        ['key' => 'high-opportunity', 'name' => 'Telecom high-opportunity page', 'trigger' => AlertRule::TRIGGER_HIGH_OPPORTUNITY_PAGE, 'severity' => 'medium', 'conditions' => ['market_pack' => 'telecom', 'min_score' => 80]],
    ],
    'scoring_models' => [
        [
            'key' => 'argusly-pr-value',
            'name' => 'Telecom Argusly PR Value',
            'weights' => [
                'source_authority' => 0.14,
                'estimated_reach' => 0.12,
                'page_visibility' => 0.12,
                'sentiment' => 0.1,
                'brand_prominence' => 0.14,
                'topic_relevance' => 0.14,
                'geo_visibility' => 0.1,
                'industry_relevance' => 0.08,
                'recency' => 0.06,
            ],
        ],
        [
            'key' => 'argusly_intelligence_score',
            'name' => 'Telecom Argusly Intelligence Score',
            'model_type' => 'page_intelligence_score',
            'model_version' => 'v1',
            'weights' => [
                'pr_value' => 0.12,
                'source_authority' => 0.11,
                'sentiment' => 0.08,
                'brand_prominence' => 0.10,
                'topic_relevance' => 0.10,
                'competitor_pressure' => 0.10,
                'market_pack_relevance' => 0.09,
                'campaign_relevance' => 0.05,
                'serp_visibility' => 0.09,
                'geo_visibility' => 0.12,
                'recency' => 0.02,
                'content_depth' => 0.02,
            ],
        ],
    ],
];
