<?php

return [
    'pages' => [
        'it-services-saas' => [
            'slugs' => ['en' => 'it-services-saas', 'nl' => 'it-services-saas'],
            'nav_order' => 50,
            'nav_label' => 'IT Services & SaaS',
            'label' => 'IT Services & SaaS',
            'short_label' => 'IT & SaaS',
            'description' => 'AI visibility and growth opportunities for software, MSP, cloud, and B2B SaaS teams.',
            'meta_title' => 'AI Visibility for IT Services and SaaS | Argusly',
            'meta_description' => 'Discover AI visibility gaps, competitor intelligence, and B2B growth opportunities for IT services, MSP, cloud, and SaaS companies.',
            'hero' => [
                'eyebrow' => 'IT Services & SaaS',
                'title' => 'Your buyers research software and services through AI before they ever reach your demo form.',
                'intro' => 'Argusly shows where SaaS, MSP, cloud, cybersecurity, and IT services companies are missing from AI answers, comparison journeys, category pages, and high-intent buying questions.',
                'challenge' => 'Crowded categories, fast-moving competitors, and AI-generated shortlists make visibility harder to defend with generic SEO content alone.',
            ],
            'metrics' => [
                ['label' => 'AI visibility', 'value' => 'Prompts, citations, answer share'],
                ['label' => 'Competitor pressure', 'value' => 'Feature, category, and comparison pages'],
                ['label' => 'Opportunity output', 'value' => 'Demo-ready topic and content queue'],
            ],
            'sections' => [
                'ai_visibility' => [
                    'title' => 'AI visibility gaps in software buying journeys',
                    'body' => 'AI systems often summarize vendors from old comparison pages, marketplaces, docs, analyst-style content, and review snippets. If your positioning, integrations, ICP, security posture, and proof are not clear, your brand can be skipped or misrepresented.',
                    'points' => ['Missing citations for category and alternative prompts', 'Weak entity coverage around integrations, compliance, and use cases', 'AI answers that mention competitors but not your product', 'Decision-stage pages that are not structured for answer engines'],
                ],
                'competitive_intelligence' => [
                    'title' => 'Competitors win attention with sharper category coverage',
                    'body' => 'SaaS and IT competitors move quickly: new alternative pages, vertical landing pages, migration guides, integration pages, pricing narratives, and security pages can change buyer perception before pipeline data reacts.',
                    'points' => ['Track new competitor comparison and alternative pages', 'Spot category and use-case claims competitors are building around', 'Compare AI answer share for buying prompts', 'Find messaging gaps around ROI, security, onboarding, and integrations'],
                ],
                'opportunity_intelligence' => [
                    'title' => 'Growth opportunities Argusly discovers',
                    'body' => 'Argusly turns weak signals into prioritized SaaS and IT growth opportunities: category expansion, comparison pages, integration content, product-led education, and refreshes that improve AI and search visibility.',
                    'points' => ['Alternative and comparison pages for high-intent buyers', 'Integration and migration content that supports solution discovery', 'Security, compliance, and implementation answer blocks', 'Refresh candidates for feature pages losing relevance'],
                ],
                'agentic_marketing' => [
                    'title' => 'Agentic marketing actions prepared for review',
                    'body' => 'Once an opportunity is approved, Argusly can prepare the execution assets your team needs without turning strategy into manual project management.',
                    'points' => ['Briefs for solution, integration, and comparison pages', 'Answer blocks and FAQ schema for AI discovery', 'Metadata, internal link, and CTA recommendations', 'Sales enablement snippets for demos and follow-up'],
                ],
            ],
            'demo_cta' => 'See AI Visibility opportunities for your SaaS company',
            'schema_opportunities' => ['SoftwareApplication', 'Service', 'FAQPage', 'BreadcrumbList'],
            'content_clusters' => ['SaaS comparison pages', 'Integration and migration guides', 'AI visibility for software categories', 'Security and compliance explainers'],
            'locales' => [
                'nl' => [
                    'nav_label' => 'IT Dienstverlening & SaaS',
                    'label' => 'IT Dienstverlening & SaaS',
                    'short_label' => 'IT & SaaS',
                    'description' => 'AI zichtbaarheid en groeikansen voor software-, MSP-, cloud- en B2B SaaS-teams.',
                ],
            ],
        ],
        'consulting-professional-services' => [
            'slugs' => ['en' => 'consulting-professional-services', 'nl' => 'consulting-professional-services'],
            'nav_order' => 60,
            'nav_label' => 'Consultancy & Professional Services',
            'label' => 'Consulting & Professional Services',
            'short_label' => 'Consulting',
            'description' => 'Market intelligence for consultants, agencies, legal, finance, and expert service firms.',
            'meta_title' => 'AI Visibility for Consulting and Professional Services | Argusly',
            'meta_description' => 'Find AI visibility gaps, competitor pressure, and B2B marketing growth opportunities for consulting and professional services firms.',
            'hero' => [
                'eyebrow' => 'Consulting & Professional Services',
                'title' => 'Expert firms need to be visible when AI explains who to trust.',
                'intro' => 'Argusly helps consulting, advisory, agency, legal, finance, and specialist service firms see whether AI systems understand their expertise, sectors, proof, and differentiators.',
                'challenge' => 'Trust is built through visible expertise, but many firms rely on broad service pages while competitors publish sharper sector, problem, and proof-led content.',
            ],
            'metrics' => [
                ['label' => 'AI visibility', 'value' => 'Expertise and trust signals'],
                ['label' => 'Competitor pressure', 'value' => 'Sector pages and thought leadership'],
                ['label' => 'Opportunity output', 'value' => 'Authority-building content queue'],
            ],
            'sections' => [
                'ai_visibility' => [
                    'title' => 'AI systems need clear proof of expertise',
                    'body' => 'Professional service buyers ask AI for shortlists, frameworks, risks, benchmarks, and specialist recommendations. Generic service pages rarely provide enough entities, examples, credentials, and sector context to be cited.',
                    'points' => ['Weak entity signals for services, industries, and outcomes', 'Missing evidence pages for methodologies, cases, and credentials', 'AI summaries that flatten your positioning into generic consultancy language', 'Few answer-ready pages for urgent buyer questions'],
                ],
                'competitive_intelligence' => [
                    'title' => 'Competitors build trust with narrow, useful expertise',
                    'body' => 'The firms that win attention often own specific problems: transformation risks, market entry, compliance change, hiring models, financial planning, or operational improvement in named sectors.',
                    'points' => ['Monitor new sector pages and advisory offers', 'Track competitor thought leadership and problem ownership', 'Compare AI mentions for specialist service prompts', 'Find gaps in proof, case studies, and methodology content'],
                ],
                'opportunity_intelligence' => [
                    'title' => 'Growth opportunities Argusly discovers',
                    'body' => 'Argusly surfaces service and sector opportunities where expertise can become visible: decision guides, executive explainers, proof pages, comparison angles, and refreshes for stale service pages.',
                    'points' => ['Sector-specific service landing pages', 'Problem-led guides for executive buyers', 'Case study and methodology pages with extractable proof', 'FAQ hubs for advisory, legal, finance, or agency buying questions'],
                ],
                'agentic_marketing' => [
                    'title' => 'Agentic marketing actions prepared for review',
                    'body' => 'Argusly can prepare governed content assets that make expertise easier to review, approve, and publish across your marketing workflow.',
                    'points' => ['Briefs for sector and service pages', 'Expert answer blocks and FAQ schema', 'Internal links between services, cases, and insights', 'CTA variants for audits, workshops, and consultations'],
                ],
            ],
            'demo_cta' => 'See AI Visibility opportunities for your consulting firm',
            'schema_opportunities' => ['ProfessionalService', 'Service', 'FAQPage', 'Review'],
            'content_clusters' => ['Sector-specific advisory pages', 'Consulting problem guides', 'Proof and methodology content', 'AI visibility for expert services'],
            'locales' => [
                'nl' => [
                    'nav_label' => 'Consultancy & Zakelijke Dienstverlening',
                    'label' => 'Consultancy & Zakelijke Dienstverlening',
                    'short_label' => 'Consultancy',
                    'description' => 'Marktintelligentie voor consultants, bureaus en specialistische zakelijke dienstverleners.',
                ],
            ],
        ],
        'recruitment-staffing' => [
            'slugs' => ['en' => 'recruitment-staffing', 'nl' => 'recruitment-staffing'],
            'nav_primary' => false,
            'label' => 'Recruitment & Staffing',
            'short_label' => 'Recruitment',
            'description' => 'AI visibility and opportunity intelligence for recruitment, staffing, and talent companies.',
            'meta_title' => 'AI Visibility for Recruitment and Staffing | Argusly',
            'meta_description' => 'Discover competitor intelligence, AI visibility gaps, and growth opportunities for recruitment, staffing, and talent acquisition firms.',
            'hero' => [
                'eyebrow' => 'Recruitment & Staffing',
                'title' => 'Employers and candidates compare staffing partners through search, AI, and niche market signals.',
                'intro' => 'Argusly shows recruitment and staffing firms where they can become visible for hiring demand, skills shortages, salary questions, market guides, and employer decision journeys.',
                'challenge' => 'Generic vacancy pages do not create durable visibility when buyers need market insight, talent availability, and proof that a recruiter understands their niche.',
            ],
            'metrics' => [
                ['label' => 'AI visibility', 'value' => 'Skills, roles, salaries, markets'],
                ['label' => 'Competitor pressure', 'value' => 'Niche and location authority'],
                ['label' => 'Opportunity output', 'value' => 'Hiring-demand content queue'],
            ],
            'sections' => [
                'ai_visibility' => [
                    'title' => 'AI visibility depends on clear talent-market authority',
                    'body' => 'AI answers can recommend staffing partners, summarize salary ranges, explain hiring bottlenecks, and compare recruitment models. Firms without structured role, sector, and location content are easy to miss.',
                    'points' => ['Missing citations for role, skill, and location prompts', 'Weak structured answers around salaries and hiring timelines', 'Little proof of niche specialization', 'Employer and candidate journeys mixed into one generic message'],
                ],
                'competitive_intelligence' => [
                    'title' => 'Competitors claim niches before demand peaks',
                    'body' => 'Recruitment competitors often build authority through salary guides, talent reports, role pages, sector hubs, and location pages that match the way employers research hiring risk.',
                    'points' => ['Track competitor role and salary content', 'Spot emerging skill and sector hiring themes', 'Compare AI mentions for staffing and recruitment prompts', 'Find weak coverage in locations, specialisms, and hiring models'],
                ],
                'opportunity_intelligence' => [
                    'title' => 'Growth opportunities Argusly discovers',
                    'body' => 'Argusly identifies content opportunities that connect employer demand with candidate supply: niche landing pages, salary explainers, hiring guides, market reports, and refreshes for underperforming pages.',
                    'points' => ['Role and skill landing pages for high-demand searches', 'Salary and hiring timeline answer blocks', 'Sector-specific employer guides', 'Candidate content that strengthens expertise signals'],
                ],
                'agentic_marketing' => [
                    'title' => 'Agentic marketing actions prepared for review',
                    'body' => 'Argusly can prepare market-specific briefs and updates so recruiters get useful assets without rebuilding the strategy from scratch every month.',
                    'points' => ['Briefs for role, sector, and location pages', 'FAQ schema for hiring and salary questions', 'Internal links between jobs, guides, and service pages', 'CTA recommendations for employer intake and candidate registration'],
                ],
            ],
            'demo_cta' => 'See AI Visibility opportunities for your recruitment firm',
            'schema_opportunities' => ['EmploymentAgency', 'JobPosting', 'FAQPage', 'LocalBusiness'],
            'content_clusters' => ['Salary and hiring guides', 'Role and skill landing pages', 'Sector recruitment pages', 'AI visibility for staffing firms'],
        ],
        'telecom-connectivity' => [
            'slugs' => ['en' => 'telecom-connectivity', 'nl' => 'telecom-connectivity'],
            'nav_order' => 10,
            'nav_label' => 'Telecom & Connectivity',
            'label' => 'Telecom & Connectivity',
            'short_label' => 'Telecom',
            'description' => 'Growth intelligence for connectivity, fiber, cloud communications, and managed network providers.',
            'meta_title' => 'AI Visibility for Telecom and Connectivity | Argusly',
            'meta_description' => 'Find AI visibility, competitor intelligence, and B2B marketing growth opportunities for telecom, connectivity, and network providers.',
            'hero' => [
                'eyebrow' => 'Telecom & Connectivity',
                'title' => 'Connectivity buyers need answers on coverage, resilience, cost, and migration risk.',
                'intro' => 'Argusly helps telecom, fiber, SD-WAN, cloud communications, and managed connectivity providers become visible when buyers research reliability, locations, contract shifts, and network transformation.',
                'challenge' => 'The market is crowded with similar claims. AI and search visibility depend on proving coverage, use cases, technical clarity, and competitive difference.',
            ],
            'metrics' => [
                ['label' => 'AI visibility', 'value' => 'Coverage, resilience, migration'],
                ['label' => 'Competitor pressure', 'value' => 'Local, technical, and pricing claims'],
                ['label' => 'Opportunity output', 'value' => 'Connectivity demand queue'],
            ],
            'sections' => [
                'ai_visibility' => [
                    'title' => 'AI answers need reliable technical and local signals',
                    'body' => 'Buyers ask AI about fiber availability, SD-WAN choices, UCaaS migration, network resilience, compliance, and vendor comparisons. Weak location, product, and proof signals make providers harder to recommend.',
                    'points' => ['Missing citations for availability and connectivity prompts', 'Unclear entity coverage around network products and regions', 'AI summaries that cannot distinguish provider strengths', 'Few answer-ready pages for migration, SLA, and resilience questions'],
                ],
                'competitive_intelligence' => [
                    'title' => 'Competitors compete on coverage, reliability, and migration confidence',
                    'body' => 'Telecom and connectivity providers win attention through local pages, product comparisons, uptime proof, implementation guidance, and clear positioning against incumbent alternatives.',
                    'points' => ['Monitor competitor coverage and location pages', 'Track claims around uptime, SLA, pricing, and migration', 'Compare AI mentions for connectivity buying prompts', 'Find gaps in technical explainers and proof assets'],
                ],
                'opportunity_intelligence' => [
                    'title' => 'Growth opportunities Argusly discovers',
                    'body' => 'Argusly surfaces opportunities tied to buyer demand: local connectivity pages, product explainers, comparison guides, migration content, and technical answer blocks.',
                    'points' => ['Fiber, SD-WAN, UCaaS, and managed network landing pages', 'Location and coverage pages with clear next steps', 'Migration and implementation guides', 'SLA, resilience, and security FAQ content'],
                ],
                'agentic_marketing' => [
                    'title' => 'Agentic marketing actions prepared for review',
                    'body' => 'Argusly prepares structured assets that help commercial and technical teams turn market signals into publishable pages and campaign handoffs.',
                    'points' => ['Briefs for local and technical service pages', 'FAQ schema for connectivity decision questions', 'Internal links across coverage, products, and cases', 'CTA variants for availability checks and network assessments'],
                ],
            ],
            'demo_cta' => 'See AI Visibility opportunities for your connectivity provider',
            'schema_opportunities' => ['Service', 'LocalBusiness', 'FAQPage', 'Product'],
            'content_clusters' => ['Fiber and connectivity availability', 'Network resilience guides', 'SD-WAN and UCaaS comparisons', 'AI visibility for telecom providers'],
            'locales' => [
                'nl' => [
                    'nav_label' => 'Telecom & Connectiviteit',
                    'label' => 'Telecom & Connectiviteit',
                    'description' => 'Growth intelligence voor connectiviteit, glasvezel, cloudcommunicatie en managed netwerkproviders.',
                    'demo_cta' => 'Bekijk AI Visibility-kansen voor je connectiviteitsprovider',
                ],
            ],
        ],
        'logistics-supply-chain' => [
            'slugs' => ['en' => 'logistics-supply-chain', 'nl' => 'logistics-supply-chain'],
            'nav_order' => 30,
            'nav_label' => 'Logistics & Supply Chain',
            'label' => 'Logistics & Supply Chain',
            'short_label' => 'Logistics',
            'description' => 'Opportunity intelligence for 3PL, transport, warehousing, fulfilment, and supply chain providers.',
            'meta_title' => 'AI Visibility for Logistics and Supply Chain | Argusly',
            'meta_description' => 'Discover AI visibility gaps, competitor intelligence, and B2B growth opportunities for logistics, 3PL, fulfilment, and supply chain companies.',
            'hero' => [
                'eyebrow' => 'Logistics & Supply Chain',
                'title' => 'Supply chain buyers search for reliability, speed, routes, capacity, and risk reduction.',
                'intro' => 'Argusly helps logistics, 3PL, warehousing, fulfilment, freight, and supply chain companies discover where buyer demand is forming and where competitors own the answer.',
                'challenge' => 'Operational credibility is difficult to prove through generic service pages. Buyers need evidence around lanes, sectors, SLAs, technology, capacity, and disruption handling.',
            ],
            'metrics' => [
                ['label' => 'AI visibility', 'value' => 'Routes, capacity, sectors, risk'],
                ['label' => 'Competitor pressure', 'value' => '3PL, freight, and fulfilment claims'],
                ['label' => 'Opportunity output', 'value' => 'Demand and route content queue'],
            ],
            'sections' => [
                'ai_visibility' => [
                    'title' => 'AI systems look for structured logistics proof',
                    'body' => 'Buyers ask AI about 3PL options, fulfilment models, freight routes, cold chain requirements, customs, lead times, and supply chain resilience. Thin service pages rarely provide enough operational context to be cited.',
                    'points' => ['Missing citations for route, sector, and service prompts', 'Weak proof around capacity, SLA, compliance, and technology', 'AI answers that favor competitors with stronger explainers', 'Limited FAQ coverage for urgent operational questions'],
                ],
                'competitive_intelligence' => [
                    'title' => 'Competitors win by owning specific lanes and use cases',
                    'body' => 'Logistics competitors build authority through route pages, sector pages, warehouse capability pages, carrier content, and disruption playbooks that match buyer concerns.',
                    'points' => ['Track competitor route, sector, and fulfilment pages', 'Monitor claims around speed, reliability, and capacity', 'Compare AI answer share for logistics service prompts', 'Find gaps in proof, certifications, and operating model content'],
                ],
                'opportunity_intelligence' => [
                    'title' => 'Growth opportunities Argusly discovers',
                    'body' => 'Argusly turns logistics signals into prioritized opportunities: route explainers, fulfilment guides, sector pages, disruption content, and refreshes for service pages that underperform.',
                    'points' => ['Route and trade-lane landing pages', '3PL, warehousing, and fulfilment decision guides', 'Sector-specific logistics pages', 'Risk, customs, and resilience answer blocks'],
                ],
                'agentic_marketing' => [
                    'title' => 'Agentic marketing actions prepared for review',
                    'body' => 'Argusly prepares the assets needed to turn operational strengths into visible, governed marketing execution.',
                    'points' => ['Briefs for lanes, sectors, and service capabilities', 'FAQ schema for logistics decision questions', 'Internal links across services, cases, and locations', 'CTA recommendations for quote, assessment, and capacity conversations'],
                ],
            ],
            'demo_cta' => 'See AI Visibility opportunities for your logistics company',
            'schema_opportunities' => ['Service', 'LocalBusiness', 'FAQPage', 'Organization'],
            'content_clusters' => ['3PL and fulfilment guides', 'Route and lane pages', 'Supply chain resilience content', 'AI visibility for logistics providers'],
            'locales' => [
                'nl' => [
                    'nav_label' => 'Logistiek & Supply Chain',
                    'label' => 'Logistiek & Supply Chain',
                    'short_label' => 'Logistiek',
                    'description' => 'Opportunity intelligence voor 3PL, transport, warehousing, fulfilment en supply chain providers.',
                ],
            ],
        ],
        'manufacturing' => [
            'slugs' => ['en' => 'manufacturing', 'nl' => 'manufacturing'],
            'nav_order' => 40,
            'nav_label' => 'Manufacturing',
            'label' => 'Manufacturing',
            'short_label' => 'Manufacturing',
            'description' => 'AI visibility and B2B growth intelligence for manufacturers and industrial suppliers.',
            'meta_title' => 'AI Visibility for Manufacturing | Argusly',
            'meta_description' => 'Find AI visibility gaps, competitor intelligence, and growth opportunities for manufacturing, OEM, component, and industrial supplier marketing.',
            'hero' => [
                'eyebrow' => 'Manufacturing',
                'title' => 'Industrial buyers research specifications, compliance, reliability, and suppliers long before sales speaks to them.',
                'intro' => 'Argusly helps manufacturers, OEMs, component suppliers, and industrial brands identify AI visibility gaps, competitor movements, and content opportunities across technical buying journeys.',
                'challenge' => 'Manufacturing websites often contain valuable information, but it is buried in PDFs, product tables, old brochures, and pages that answer engines cannot easily interpret.',
            ],
            'metrics' => [
                ['label' => 'AI visibility', 'value' => 'Products, specs, standards, use cases'],
                ['label' => 'Competitor pressure', 'value' => 'Technical and sector authority'],
                ['label' => 'Opportunity output', 'value' => 'Industrial buying content queue'],
            ],
            'sections' => [
                'ai_visibility' => [
                    'title' => 'AI systems need product, standard, and application clarity',
                    'body' => 'Buyers ask AI about materials, tolerances, certifications, use cases, lead times, maintenance, and supplier comparisons. If this context lives only in PDFs or thin product grids, it is harder to cite and reuse.',
                    'points' => ['Missing citations for technical and application prompts', 'Weak entity coverage for products, standards, and sectors', 'AI answers that miss differentiators like quality, compliance, or capacity', 'Limited answer blocks for engineering and procurement questions'],
                ],
                'competitive_intelligence' => [
                    'title' => 'Competitors build visibility through technical education',
                    'body' => 'Industrial competitors gain attention with application guides, standards explainers, product comparison pages, downloadable specs, and sector pages that help engineers and procurement teams decide.',
                    'points' => ['Track competitor product and application content', 'Monitor claims around quality, compliance, capacity, and lead times', 'Compare AI mentions for product category prompts', 'Find gaps in specs, proof, and sector coverage'],
                ],
                'opportunity_intelligence' => [
                    'title' => 'Growth opportunities Argusly discovers',
                    'body' => 'Argusly surfaces opportunities that make technical strengths visible: application pages, product explainers, standards content, procurement guides, and refreshes for buried product information.',
                    'points' => ['Application and sector landing pages', 'Technical answer blocks for standards and specs', 'Product comparison and selection guides', 'Refreshes for PDF-heavy or outdated product pages'],
                ],
                'agentic_marketing' => [
                    'title' => 'Agentic marketing actions prepared for review',
                    'body' => 'Argusly can prepare structured briefs and content improvements while keeping technical review and approval in the workflow.',
                    'points' => ['Briefs for product, application, and sector pages', 'FAQ schema for engineering and procurement questions', 'Internal links across product families and use cases', 'CTA variants for quote requests, samples, and technical consultations'],
                ],
            ],
            'demo_cta' => 'See AI Visibility opportunities for your manufacturing company',
            'schema_opportunities' => ['Product', 'FAQPage', 'HowTo', 'Organization'],
            'content_clusters' => ['Product and application guides', 'Standards and compliance explainers', 'Industrial buyer FAQs', 'AI visibility for manufacturers'],
            'locales' => [
                'nl' => [
                    'nav_label' => 'Productie & Manufacturing',
                    'label' => 'Productie & Manufacturing',
                    'description' => 'AI zichtbaarheid en B2B growth intelligence voor producenten en industriele leveranciers.',
                ],
            ],
        ],
        'energy-industrial-services' => [
            'slugs' => ['en' => 'energy-industrial-services', 'nl' => 'energy-industrial-services'],
            'nav_order' => 20,
            'nav_label' => 'Energy, Oil & Gas',
            'label' => 'Energy & Industrial Services',
            'short_label' => 'Energy',
            'description' => 'Market intelligence for energy, utilities, installation, maintenance, and industrial service providers.',
            'meta_title' => 'AI Visibility for Energy and Industrial Services | Argusly',
            'meta_description' => 'Discover AI visibility gaps, competitor intelligence, and B2B marketing opportunities for energy and industrial services companies.',
            'hero' => [
                'eyebrow' => 'Energy & Industrial Services',
                'title' => 'Energy and industrial buyers need credible answers around risk, regulation, uptime, and transition.',
                'intro' => 'Argusly helps energy, utilities, installation, maintenance, engineering, and industrial service providers identify where market demand, AI visibility, and competitor claims are shifting.',
                'challenge' => 'Complex services are often explained in vague capability language while buyers need proof, safety context, compliance clarity, sector knowledge, and practical next steps.',
            ],
            'metrics' => [
                ['label' => 'AI visibility', 'value' => 'Risk, compliance, transition, uptime'],
                ['label' => 'Competitor pressure', 'value' => 'Sector and regulation claims'],
                ['label' => 'Opportunity output', 'value' => 'Industrial service content queue'],
            ],
            'sections' => [
                'ai_visibility' => [
                    'title' => 'AI visibility requires trustworthy technical context',
                    'body' => 'Buyers ask AI about maintenance strategies, energy transition options, safety obligations, compliance, infrastructure upgrades, and industrial service providers. Without structured proof, your expertise can be invisible.',
                    'points' => ['Missing citations for regulation, safety, and service prompts', 'Weak entity coverage for sectors, assets, and service lines', 'AI summaries that overlook differentiators like certifications or uptime proof', 'Few answer-ready pages for urgent operational questions'],
                ],
                'competitive_intelligence' => [
                    'title' => 'Competitors claim authority on transition, uptime, and compliance',
                    'body' => 'Energy and industrial competitors build visibility with regulation explainers, sector pages, maintenance guides, safety content, case studies, and capability pages tied to buyer risk.',
                    'points' => ['Track competitor service and sector pages', 'Monitor claims around compliance, safety, uptime, and sustainability', 'Compare AI answer share for industrial service prompts', 'Find gaps in proof, cases, and technical explainers'],
                ],
                'opportunity_intelligence' => [
                    'title' => 'Growth opportunities Argusly discovers',
                    'body' => 'Argusly identifies content opportunities around regulation changes, maintenance demand, sector applications, energy transition questions, and service pages that need stronger proof.',
                    'points' => ['Regulation and compliance explainers', 'Maintenance, uptime, and asset lifecycle guides', 'Sector-specific energy and industrial service pages', 'Case-led proof pages for complex buying committees'],
                ],
                'agentic_marketing' => [
                    'title' => 'Agentic marketing actions prepared for review',
                    'body' => 'Argusly prepares technical marketing assets for review while keeping governance, approval, and risk-sensitive messaging under control.',
                    'points' => ['Briefs for regulation, service, and sector pages', 'FAQ schema for safety, compliance, and maintenance questions', 'Internal links across services, cases, and technical resources', 'CTA variants for site assessments, audits, and consultation requests'],
                ],
            ],
            'demo_cta' => 'See AI Visibility opportunities for your industrial services company',
            'schema_opportunities' => ['Service', 'FAQPage', 'Organization', 'Article'],
            'content_clusters' => ['Energy transition explainers', 'Industrial maintenance guides', 'Compliance and safety content', 'AI visibility for industrial services'],
            'locales' => [
                'nl' => [
                    'nav_label' => 'Energie, Olie & Gas',
                    'label' => 'Energie, Olie & Gas',
                    'short_label' => 'Energie',
                    'description' => 'Marktintelligentie voor energie, utilities, installatie, onderhoud en industriele dienstverlening.',
                ],
            ],
        ],
        'automotive' => [
            'slugs' => ['en' => 'automotive', 'nl' => 'automotive'],
            'nav_order' => 70,
            'nav_label' => 'Automotive',
            'label' => 'Automotive',
            'short_label' => 'Automotive',
            'description' => 'AI visibility, opportunity intelligence, and autonomous marketing for automotive organizations.',
            'meta_title' => 'AI Visibility, Opportunity Intelligence and Autonomous Marketing for Automotive | Argusly',
            'meta_description' => 'Improve Automotive AI Visibility with marketing intelligence, AI search visibility, generative engine optimization, and opportunity intelligence for automotive organizations.',
            'hero' => [
                'eyebrow' => 'Automotive',
                'title' => 'Accelerate automotive growth with AI visibility and market intelligence.',
                'intro' => 'Argusly helps automotive organizations discover opportunities, increase visibility in AI systems, and organize marketing activities autonomously.',
                'challenge' => 'Automotive buyers, fleet teams, and mobility customers compare options across dealers, importers, platforms, leasing providers, software vendors, and AI-assisted research journeys.',
            ],
            'metrics' => [
                ['label' => 'AI Visibility', 'value' => 'AI search visibility, GEO, citations'],
                ['label' => 'Opportunity Intelligence', 'value' => 'Market, topic, and competitor signals'],
                ['label' => 'Autonomous Marketing', 'value' => 'Content, campaigns, distribution'],
            ],
            'challenges' => [
                'Increasing competition between dealers, importers and marketplaces',
                'Changing search behavior toward AI systems',
                'Limited visibility of products, services and expertise',
                'Fragmented marketing operations',
                'Lack of insight into emerging opportunities and competitor activity',
            ],
            'sections' => [
                'ai_visibility' => [
                    'title' => 'Increase visibility across AI search engines and generative AI systems.',
                    'body' => 'Automotive buyers increasingly use AI systems to compare models, services, providers, platforms, software, leasing options, mobility solutions, and fleet management approaches. Argusly helps make automotive expertise easier for these systems to find, cite, and represent correctly.',
                    'points' => ['AI Search Visibility Automotive coverage', 'Generative Engine Optimization Automotive workflows', 'Entity clarity for models, services, and expertise', 'Answer-ready content for commercial automotive journeys'],
                ],
                'competitive_intelligence' => [
                    'title' => 'Track competitor movement across dealers, importers, platforms, and service providers.',
                    'body' => 'Argusly monitors market signals that show where competitors are building visibility, claiming topics, launching pages, and shaping buyer perception before pipeline data reacts.',
                    'points' => ['Dealer, importer, and marketplace positioning', 'Service and software category movement', 'Competitor content and topic ownership', 'AI answer share and citation gaps'],
                ],
                'opportunity_intelligence' => [
                    'title' => 'Identify emerging market opportunities, topics and competitive movements.',
                    'body' => 'Argusly turns automotive market signals into prioritized opportunities for content, campaigns, landing pages, internal links, and visibility improvements.',
                    'points' => ['Automotive Opportunity Intelligence signals', 'Emerging model, mobility, and fleet topics', 'New service and software demand patterns', 'Prioritized opportunities for marketing execution'],
                ],
                'agentic_marketing' => [
                    'title' => 'Coordinate content, campaigns and distribution from a single platform.',
                    'body' => 'Autonomous Marketing helps automotive teams move from opportunity detection to governed execution, with reviewable briefs, content updates, campaign assets, and distribution paths.',
                    'points' => ['Content briefs for automotive journeys', 'Campaign planning around opportunity signals', 'Distribution and internal linking recommendations', 'Governed workflows for fragmented teams'],
                ],
            ],
            'use_cases' => ['Dealer groups', 'Importers', 'Leasing companies', 'Automotive software providers', 'Mobility providers', 'Automotive service organizations', 'Fleet management companies'],
            'demo_cta' => 'Request AI Visibility Scan',
            'schema_opportunities' => ['AutoDealer', 'Product', 'Service', 'FAQPage'],
            'content_clusters' => ['Automotive AI Visibility', 'Automotive Marketing Intelligence', 'AI Search Visibility Automotive', 'Generative Engine Optimization Automotive', 'Automotive Opportunity Intelligence'],
            'locales' => [
                'nl' => [
                    'description' => 'AI zichtbaarheid, opportunity intelligence en autonomous marketing voor automotive organisaties.',
                    'meta_title' => 'AI Visibility, Opportunity Intelligence en Autonomous Marketing voor Automotive | Argusly',
                    'meta_description' => 'Verbeter Automotive AI Visibility met Automotive Marketing, Automotive AI Search, Automotive GEO en Automotive Opportunity Intelligence.',
                    'hero' => [
                        'eyebrow' => 'Automotive',
                        'title' => 'Versnel groei in automotive met AI zichtbaarheid en marktintelligentie.',
                        'intro' => 'Argusly helpt automotive organisaties kansen te ontdekken, zichtbaarheid in AI systemen te vergroten en marketingactiviteiten slimmer te organiseren.',
                        'challenge' => 'Automotive kopers, fleet teams en mobiliteitsklanten vergelijken opties via dealers, importeurs, platformen, leasebedrijven, softwareleveranciers en AI-gedreven research journeys.',
                    ],
                    'metrics' => [
                        ['label' => 'AI Visibility', 'value' => 'AI search, Automotive GEO, citations'],
                        ['label' => 'Opportunity Intelligence', 'value' => 'Markt-, topic- en concurrentiesignalen'],
                        ['label' => 'Autonomous Marketing', 'value' => 'Content, campagnes, distributie'],
                    ],
                    'challenges' => [
                        'Toenemende concurrentie tussen dealers, importeurs en platformen',
                        'Veranderend zoekgedrag richting AI systemen',
                        'Moeilijke zichtbaarheid van modellen, diensten en expertise',
                        'Versnipperde marketingactiviteiten',
                        'Beperkt inzicht in marktkansen en concurrentiebewegingen',
                    ],
                    'sections' => [
                        'ai_visibility' => [
                            'title' => 'Vergroot zichtbaarheid binnen AI zoekmachines en generatieve AI systemen.',
                            'body' => 'Automotive kopers gebruiken steeds vaker AI systemen om modellen, diensten, aanbieders, platformen, leaseopties, mobiliteitsoplossingen en fleetmanagement te vergelijken. Argusly helpt automotive expertise vindbaar, citeerbaar en correct representeerbaar te maken.',
                            'points' => ['Automotive AI Search zichtbaarheid', 'Automotive GEO workflows', 'Entity clarity voor modellen, diensten en expertise', 'Answer-ready content voor commerciële automotive journeys'],
                        ],
                        'competitive_intelligence' => [
                            'title' => 'Volg concurrentiebewegingen bij dealers, importeurs, platformen en dienstverleners.',
                            'body' => 'Argusly monitort marktsignalen die laten zien waar concurrenten zichtbaarheid opbouwen, topics claimen, pagina\'s lanceren en buyer perception vormen voordat pipeline-data reageert.',
                            'points' => ['Positionering van dealers, importeurs en marketplaces', 'Beweging in service- en softwarecategorieen', 'Concurrentiecontent en topic ownership', 'AI answer share en citation gaps'],
                        ],
                        'opportunity_intelligence' => [
                            'title' => 'Ontdek opkomende marktkansen, onderwerpen en concurrentiebewegingen.',
                            'body' => 'Argusly vertaalt automotive marktsignalen naar geprioriteerde kansen voor content, campagnes, landingspagina\'s, interne links en visibility improvements.',
                            'points' => ['Automotive Opportunity Intelligence signalen', 'Opkomende model-, mobiliteits- en fleettopics', 'Nieuwe vraagpatronen rond diensten en software', 'Geprioriteerde kansen voor marketinguitvoering'],
                        ],
                        'agentic_marketing' => [
                            'title' => 'Organiseer content, campagnes en distributie vanuit één platform.',
                            'body' => 'Autonomous Marketing helpt automotive teams van opportunity detection naar governed execution, met reviewbare briefs, contentupdates, campagne-assets en distributieroutes.',
                            'points' => ['Contentbriefs voor automotive journeys', 'Campagneplanning rond opportunity signals', 'Distributie- en internal linking aanbevelingen', 'Governed workflows voor versnipperde teams'],
                        ],
                    ],
                    'use_cases' => ['Dealerorganisaties', 'Importeurs', 'Leasebedrijven', 'Automotive softwareleveranciers', 'Mobiliteitsaanbieders', 'Automotive dienstverleners', 'Fleetmanagement organisaties'],
                    'demo_cta' => 'Vraag een AI Visibility Scan aan',
                    'content_clusters' => ['Automotive AI Visibility', 'Automotive Marketing', 'Automotive AI Search', 'Automotive GEO', 'Automotive Opportunity Intelligence'],
                ],
            ],
        ],
    ],
];
