<?php

return [
    'types' => [
        'article' => [
            'label' => 'Article',
            'badge' => 'ARTICLE',
            'description' => 'Long-form website content for authority, search, and AI visibility.',
            'category' => 'content',
            'purpose' => 'primary_content',
            'icon' => 'file-text',
            'color' => 'sky',
            'group' => 'content_creation',
            'publishable' => true,
        ],
        'linkedin_post' => [
            'label' => 'LinkedIn Post',
            'badge' => 'LINKEDIN',
            'description' => 'Channel-specific social copy for LinkedIn distribution.',
            'category' => 'distribution',
            'purpose' => 'distribution_content',
            'icon' => 'linkedin',
            'color' => 'blue',
            'group' => 'distribution',
            'publishable' => true,
        ],
        'instagram_post' => [
            'label' => 'Instagram Post',
            'badge' => 'INSTAGRAM',
            'description' => 'Channel-specific social copy and creative direction for Instagram.',
            'category' => 'distribution',
            'purpose' => 'distribution_content',
            'icon' => 'instagram',
            'color' => 'rose',
            'group' => 'distribution',
            'publishable' => true,
        ],
        'newsletter_snippet' => [
            'label' => 'Newsletter Snippet',
            'badge' => 'NEWSLETTER',
            'description' => 'Reusable campaign excerpt for newsletter placement.',
            'category' => 'distribution',
            'purpose' => 'distribution_content',
            'icon' => 'mail',
            'color' => 'amber',
            'group' => 'distribution',
            'publishable' => false,
        ],
        'faq_block' => [
            'label' => 'FAQ Block',
            'badge' => 'FAQ',
            'description' => 'Structured question-and-answer content for conversion and answer surfaces.',
            'category' => 'knowledge',
            'purpose' => 'aeo_content',
            'icon' => 'badge-help',
            'color' => 'emerald',
            'group' => 'knowledge',
            'publishable' => true,
        ],
        'answer_block' => [
            'label' => 'Answer Block',
            'badge' => 'ANSWER',
            'description' => 'Concise answer content for AI visibility, snippets, and page reuse.',
            'category' => 'knowledge',
            'purpose' => 'knowledge_content',
            'icon' => 'message-square-text',
            'color' => 'teal',
            'group' => 'knowledge',
            'publishable' => true,
        ],
        'landing_page_section' => [
            'label' => 'Landing Page Section',
            'badge' => 'PAGE',
            'description' => 'Structured website section for campaign or conversion pages.',
            'category' => 'conversion',
            'purpose' => 'conversion_content',
            'icon' => 'layout-template',
            'color' => 'violet',
            'group' => 'conversion',
            'publishable' => true,
        ],
        'campaign_brief' => [
            'label' => 'Campaign Brief',
            'badge' => 'BRIEF',
            'description' => 'Planning asset that defines campaign intent, audience, and execution rules.',
            'category' => 'campaign',
            'purpose' => 'campaign_content',
            'icon' => 'clipboard-list',
            'color' => 'slate',
            'group' => 'campaign_execution',
            'publishable' => false,
        ],
        'case_study' => [
            'label' => 'Case Study',
            'badge' => 'CASE',
            'description' => 'Proof asset for outcomes, credibility, and sales enablement.',
            'category' => 'resource',
            'purpose' => 'conversion_content',
            'icon' => 'briefcase-business',
            'color' => 'indigo',
            'group' => 'conversion',
            'publishable' => true,
        ],
        'whitepaper' => [
            'label' => 'Whitepaper',
            'badge' => 'WHITEPAPER',
            'description' => 'Deep resource asset for authority, education, and lead capture.',
            'category' => 'resource',
            'purpose' => 'primary_content',
            'icon' => 'book-open-text',
            'color' => 'cyan',
            'group' => 'content_creation',
            'publishable' => true,
        ],
        'email_content' => [
            'label' => 'Email Content',
            'badge' => 'EMAIL',
            'description' => 'Email copy for nurture, launch, and campaign follow-up workflows.',
            'category' => 'distribution',
            'purpose' => 'distribution_content',
            'icon' => 'mail-check',
            'color' => 'amber',
            'group' => 'distribution',
            'publishable' => false,
        ],
        'cta_block' => [
            'label' => 'CTA Block',
            'badge' => 'CTA',
            'description' => 'Conversion prompt for website, content, or campaign journeys.',
            'category' => 'conversion',
            'purpose' => 'conversion_content',
            'icon' => 'mouse-pointer-click',
            'color' => 'fuchsia',
            'group' => 'conversion',
            'publishable' => false,
        ],
        'market_page_content' => [
            'label' => 'Market Page Content',
            'badge' => 'MARKET',
            'description' => 'Structured market page content for programmatic visibility pages.',
            'category' => 'content',
            'purpose' => 'seo_content',
            'icon' => 'globe-2',
            'color' => 'sky',
            'group' => 'content_creation',
            'publishable' => true,
        ],
        'solution_page_content' => [
            'label' => 'Solution Page Content',
            'badge' => 'SOLUTION',
            'description' => 'Structured solution page content for positioning and conversion.',
            'category' => 'conversion',
            'purpose' => 'conversion_content',
            'icon' => 'panel-top',
            'color' => 'violet',
            'group' => 'conversion',
            'publishable' => true,
        ],
        'founder_post' => [
            'label' => 'Founder Post',
            'badge' => 'FOUNDER',
            'description' => 'Founder-led social narrative for campaign distribution.',
            'category' => 'distribution',
            'purpose' => 'distribution_content',
            'icon' => 'user-round-pen',
            'color' => 'blue',
            'group' => 'distribution',
            'publishable' => true,
        ],
    ],

    'future_types' => [
        'facebook_post',
        'x_post',
        'reddit_post',
        'youtube_script',
        'podcast_outline',
        'webinar_content',
        'ad_copy',
    ],
];
