<?php

return [
    'network_linking' => (bool) env('ARGUSLY_FEATURE_NETWORK_LINKING', false),
    'draft_link_suggestions' => (bool) env('ARGUSLY_FEATURE_DRAFT_LINK_SUGGESTIONS', false),
    'link_intelligence_jobs' => (bool) env('ARGUSLY_FEATURE_LINK_INTELLIGENCE_JOBS', false),
    'research_layer' => (bool) env('ARGUSLY_FEATURE_RESEARCH_LAYER', false),
    'brief_intelligence' => (bool) env('ARGUSLY_FEATURE_BRIEF_INTELLIGENCE', false),
    'brief_templates' => (bool) env('ARGUSLY_FEATURE_BRIEF_TEMPLATES', false),
    'content_network_analysis' => (bool) env('ARGUSLY_FEATURE_CONTENT_NETWORK_ANALYSIS', false),
    'mos_canonical_content_opportunity_brief_writer' => (bool) env('ARGUSLY_FEATURE_MOS_CANONICAL_CONTENT_OPPORTUNITY_BRIEF_WRITER', false),
    'mos_canonical_content_opportunity_lifecycle_sync' => (bool) env('ARGUSLY_FEATURE_MOS_CANONICAL_CONTENT_OPPORTUNITY_LIFECYCLE_SYNC', false),
    'mos_canonical_content_opportunity_growth_writer' => (bool) env('ARGUSLY_FEATURE_MOS_CANONICAL_CONTENT_OPPORTUNITY_GROWTH_WRITER', false),
    'mos_canonical_content_opportunity_autopilot_writer' => (bool) env('ARGUSLY_FEATURE_MOS_CANONICAL_CONTENT_OPPORTUNITY_AUTOPILOT_WRITER', false),
    'mos_canonical_content_opportunity_action_ownership' => (bool) env('ARGUSLY_FEATURE_MOS_CANONICAL_CONTENT_OPPORTUNITY_ACTION_OWNERSHIP', false),
    'mos_agentic_marketing_opportunity_bridge_writer' => (bool) env('ARGUSLY_FEATURE_MOS_AGENTIC_MARKETING_OPPORTUNITY_BRIDGE_WRITER', false),
    'mos_agentic_marketing_opportunity_signal_promotion' => (bool) env('ARGUSLY_FEATURE_MOS_AGENTIC_MARKETING_OPPORTUNITY_SIGNAL_PROMOTION', false),
    'mos_agentic_execution_canonical_metadata_writer' => (bool) env('ARGUSLY_FEATURE_MOS_AGENTIC_EXECUTION_CANONICAL_METADATA_WRITER', false),
    'mos_agentic_planner_canonical_experiment' => (bool) env('ARGUSLY_FEATURE_MOS_AGENTIC_PLANNER_CANONICAL_EXPERIMENT', false),
    'mos_agentic_planner_canonical_apply_experiment' => (bool) env('ARGUSLY_FEATURE_MOS_AGENTIC_PLANNER_CANONICAL_APPLY_EXPERIMENT', false),
    'mos_agentic_planner_canonical_shadow' => (bool) env('ARGUSLY_FEATURE_MOS_AGENTIC_PLANNER_CANONICAL_SHADOW', false),
    'mos_agentic_planner_canonical_default_selection_preview' => (bool) env('ARGUSLY_FEATURE_MOS_AGENTIC_PLANNER_CANONICAL_DEFAULT_SELECTION_PREVIEW', false),
    'mos_agentic_planner_canonical_default_selection_experiment' => (bool) env('ARGUSLY_FEATURE_MOS_AGENTIC_PLANNER_CANONICAL_DEFAULT_SELECTION_EXPERIMENT', false),
    'agentic_marketing' => (bool) env('ARGUSLY_FEATURE_AGENTIC_MARKETING', true),
    'signal_intelligence' => (bool) env('ARGUSLY_SIGNAL_INTELLIGENCE_ENABLED', true),
];
