<?php

return [
    'subprocessors' => [
        'providers' => [
            [
                'name' => 'OpenAI',
                'legal_entity' => 'OpenAI, L.L.C.',
                'service_category' => 'ai_llm_infrastructure',
                'purpose' => 'ai_content_generation',
                'location' => 'san_francisco_ca_us',
                'website' => 'https://openai.com',
                'privacy_url' => 'https://openai.com/policies/privacy-policy',
                'dpa_url' => 'https://openai.com/policies/data-processing-addendum',
                'registered_address' => null,
                'last_updated' => '2026-03-11',
            ],
            [
                'name' => 'Anthropic',
                'legal_entity' => 'Anthropic, PBC',
                'service_category' => 'ai_llm_infrastructure',
                'purpose' => 'ai_content_generation',
                'location' => 'san_francisco_ca_us',
                'website' => 'https://www.anthropic.com',
                'privacy_url' => 'https://www.anthropic.com/privacy',
                'dpa_url' => 'https://www.anthropic.com/legal/commercial-terms',
                'registered_address' => null,
                'last_updated' => '2026-03-11',
            ],
            [
                'name' => 'Mistral AI',
                'legal_entity' => 'Mistral AI',
                'service_category' => 'ai_llm_infrastructure',
                'purpose' => 'ai_content_generation',
                'location' => 'paris_fr',
                'website' => 'https://mistral.ai',
                'privacy_url' => 'https://mistral.ai/privacy-policy',
                'dpa_url' => 'https://legal.mistral.ai/terms/data-processing-addendum',
                'registered_address' => '15 rue des Halles, 75001 Paris, France',
                'last_updated' => '2026-03-11',
            ],
            [
                'name' => 'Google AI',
                'legal_entity' => 'Google LLC',
                'service_category' => 'ai_llm_infrastructure',
                'purpose' => 'google_ai_content_generation',
                'location' => 'mountain_view_ca_us',
                'website' => 'https://ai.google',
                'privacy_url' => 'https://policies.google.com/privacy',
                'dpa_url' => 'https://business.safety.google/adsprocessorterms',
                'registered_address' => null,
                'last_updated' => '2026-03-11',
            ],
            [
                'name' => 'Sentry',
                'legal_entity' => 'Functional Software, Inc.',
                'service_category' => 'error_monitoring',
                'purpose' => 'error_monitoring',
                'location' => 'san_francisco_ca_us',
                'website' => 'https://sentry.io',
                'privacy_url' => 'https://sentry.io/privacy/',
                'dpa_url' => 'https://sentry.io/legal/dpa/',
                'registered_address' => null,
                'last_updated' => '2026-03-11',
            ],
            [
                'name' => 'Mailgun',
                'legal_entity' => 'Mailgun Technologies, Inc.',
                'service_category' => 'transactional_email',
                'purpose' => 'transactional_email',
                'location' => 'united_states',
                'website' => 'https://www.mailgun.com',
                'privacy_url' => 'https://www.mailgun.com/legal/privacy-policy/',
                'dpa_url' => 'https://www.mailgun.com/legal/data-processing-addendum/',
                'registered_address' => null,
                'last_updated' => '2026-03-11',
            ],
            [
                'name' => 'Mollie',
                'legal_entity' => 'Mollie B.V.',
                'service_category' => 'payments',
                'purpose' => 'payments',
                'location' => 'amsterdam_nl',
                'website' => 'https://www.mollie.com',
                'privacy_url' => 'https://www.mollie.com/privacy',
                'dpa_url' => 'https://www.mollie.com/en/privacy',
                'registered_address' => null,
                'last_updated' => '2026-03-11',
            ],
        ],
    ],
];
