<?php

return [
    'app' => [
        [
            'label' => 'Dashboard',
            'items' => [
                [
                    'key' => 'dashboard',
                    'label' => 'Dashboard',
                    'description' => 'Account and brand command center.',
                    'route' => 'dashboard',
                    'active' => ['dashboard'],
                    'modules' => ['core'],
                    'permission' => 'view_dashboard',
                    'icon' => 'layout-dashboard',
                ],
            ],
        ],
        [
            'label' => 'Intelligence',
            'items' => [
                [
                    'key' => 'intelligence',
                    'label' => 'Intelligence',
                    'description' => 'Signals, narratives, recommendations and notifications.',
                    'route' => 'app.intelligence',
                    'active' => ['app.intelligence*', 'app.recommendations.*', 'app.notifications*'],
                    'modules' => ['core'],
                    'permission' => 'view_dashboard',
                    'icon' => 'sparkles',
                    'children' => [
                        ['label' => 'Feed', 'route' => 'app.intelligence', 'active' => ['app.intelligence']],
                        ['label' => 'Signals', 'route' => 'app.intelligence.signals', 'active' => ['app.intelligence.signals']],
                        ['label' => 'Narratives', 'route' => 'app.narratives.index', 'active' => ['app.narratives.*']],
                        ['label' => 'Recommendations', 'route' => 'app.intelligence.recommendations', 'active' => ['app.intelligence.recommendations', 'app.recommendations.*']],
                        ['label' => 'Notifications', 'route' => 'app.notifications', 'active' => ['app.notifications*']],
                    ],
                ],
                [
                    'key' => 'visibility',
                    'label' => 'Visibility',
                    'description' => 'AI visibility, search performance, citations and prompts.',
                    'route' => 'app.visibility',
                    'active' => ['app.visibility*', 'app.search-performance'],
                    'modules' => ['visibility'],
                    'permission' => 'view_visibility',
                    'icon' => 'radar',
                    'children' => [
                        ['label' => 'AI Visibility', 'route' => 'app.visibility', 'active' => ['app.visibility']],
                        ['label' => 'Search Performance', 'route' => 'app.search-performance', 'active' => ['app.visibility.search', 'app.search-performance']],
                        ['label' => 'Citations', 'route' => 'app.visibility.citations', 'active' => ['app.visibility.citations']],
                        ['label' => 'Prompt Monitoring', 'route' => 'app.visibility.prompts', 'active' => ['app.visibility.prompts']],
                    ],
                ],
                [
                    'key' => 'research',
                    'label' => 'Research',
                    'description' => 'Entities, topics, mentions, competitors and source registry.',
                    'route' => 'app.topics.index',
                    'active' => ['app.research.*', 'app.entities.*', 'app.topics.*', 'app.mentions*', 'app.competitors', 'app.sources.*'],
                    'modules' => ['core', 'visibility', 'competitive_intelligence'],
                    'permission' => 'view_dashboard',
                    'icon' => 'search',
                    'children' => [
                        ['label' => 'Entities', 'route' => 'app.entities.index', 'active' => ['app.research.entities*', 'app.entities.*'], 'modules' => ['core'], 'permission' => 'view_dashboard'],
                        ['label' => 'Topics', 'route' => 'app.topics.index', 'active' => ['app.research.topics*', 'app.topics.*'], 'modules' => ['core'], 'permission' => 'view_dashboard'],
                        ['label' => 'Mentions', 'route' => 'app.mentions', 'active' => ['app.research.mentions*', 'app.mentions*'], 'modules' => ['visibility'], 'permission' => 'view_visibility'],
                        ['label' => 'Competitors', 'route' => 'app.competitors', 'active' => ['app.research.competitors*', 'app.competitors'], 'modules' => ['competitive_intelligence'], 'permission' => 'view_competitive_intelligence'],
                        ['label' => 'Sources', 'route' => 'app.sources.index', 'active' => ['app.research.sources*', 'app.sources.*'], 'modules' => ['core'], 'permission' => 'manage_account'],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Operations',
            'items' => [
                [
                    'key' => 'content',
                    'label' => 'Content',
                    'description' => 'Content Engine library, distribution and lifecycle.',
                    'route' => 'app.content.index',
                    'active' => ['app.content.*', 'app.distribution'],
                    'modules' => ['content'],
                    'permission' => 'view_content',
                    'icon' => 'file-text',
                    'children' => [
                        ['label' => 'Library', 'route' => 'app.content.index', 'active' => ['app.content.index', 'app.content.show', 'app.content.create', 'app.content.edit']],
                        ['label' => 'Distribution', 'route' => 'app.distribution', 'active' => ['app.content.distribution', 'app.distribution']],
                        ['label' => 'Answer Blocks', 'route' => 'app.content.answer-blocks.index', 'active' => ['app.content.answer-blocks.*']],
                        ['label' => 'Audits', 'route' => 'app.content.audits', 'active' => ['app.content.audits']],
                        ['label' => 'Lifecycle', 'route' => 'app.content.lifecycle.index', 'active' => ['app.content.lifecycle.index']],
                        ['label' => 'Translations', 'route' => 'app.content.translations', 'active' => ['app.content.translations']],
                    ],
                ],
                [
                    'key' => 'marketing',
                    'label' => 'Marketing',
                    'description' => 'Campaigns, calendar, tasks, briefings, newsletters and social publishing.',
                    'route' => 'app.marketing',
                    'active' => ['app.marketing*', 'app.campaigns*', 'app.calendar*', 'app.briefings*', 'app.newsletters*', 'app.social-posts*', 'app.audiences*'],
                    'modules' => ['campaigns', 'marketing_os', 'content'],
                    'permission' => 'view_campaigns',
                    'icon' => 'megaphone',
                    'children' => [
                        ['label' => 'Campaigns', 'route' => 'app.campaigns', 'active' => ['app.marketing.campaigns*', 'app.campaigns*'], 'modules' => ['campaigns'], 'permission' => 'view_campaigns'],
                        ['label' => 'Calendar', 'route' => 'app.calendar', 'active' => ['app.marketing.calendar*', 'app.calendar*'], 'modules' => ['campaigns', 'marketing_os'], 'permission' => 'view_campaigns'],
                        ['label' => 'Tasks', 'route' => 'app.marketing.tasks', 'active' => ['app.marketing.tasks'], 'modules' => ['campaigns', 'marketing_os'], 'permission' => 'view_campaigns'],
                        ['label' => 'Briefings', 'route' => 'app.briefings', 'active' => ['app.marketing.briefings*', 'app.briefings*'], 'modules' => ['campaigns', 'marketing_os'], 'permission' => 'view_campaigns'],
                        ['label' => 'Newsletters', 'route' => 'app.newsletters', 'active' => ['app.marketing.newsletters*', 'app.newsletters*'], 'modules' => ['campaigns', 'marketing_os'], 'permission' => 'view_campaigns'],
                        ['label' => 'Social Posts', 'route' => 'app.social-posts.index', 'active' => ['app.marketing.social-posts*', 'app.social-posts*'], 'modules' => ['content'], 'permission' => 'view_content'],
                        ['label' => 'Audiences', 'route' => 'app.audiences', 'active' => ['app.marketing.audiences*', 'app.audiences*'], 'modules' => ['campaigns', 'marketing_os'], 'permission' => 'view_campaigns'],
                    ],
                ],
                [
                    'key' => 'agents',
                    'label' => 'Agents',
                    'description' => 'Agents, tasks, runs and automations.',
                    'route' => 'app.agents',
                    'active' => ['app.agents*', 'app.automations'],
                    'modules' => ['agentic_content', 'agentic_social'],
                    'permission' => 'view_agents',
                    'icon' => 'bot',
                    'children' => [
                        ['label' => 'Agents', 'route' => 'app.agents', 'active' => ['app.agents']],
                        ['label' => 'Agent Tasks', 'route' => 'app.agents.tasks', 'active' => ['app.agents.tasks']],
                        ['label' => 'Runs', 'route' => 'app.agents.runs', 'active' => ['app.agents.runs']],
                        ['label' => 'Automations', 'route' => 'app.automations', 'active' => ['app.agents.automations', 'app.automations']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Relationships',
            'items' => [
                [
                    'key' => 'relationships',
                    'label' => 'Relationships',
                    'description' => 'Contacts, organizations and relationship graph.',
                    'route' => 'app.relationships',
                    'active' => ['app.relationships*'],
                    'modules' => ['core'],
                    'permission' => 'view_dashboard',
                    'icon' => 'network',
                    'children' => [
                        ['label' => 'Contacts', 'route' => 'app.relationships.contacts', 'active' => ['app.relationships.contacts*']],
                        ['label' => 'Organizations', 'route' => 'app.relationships.organizations', 'active' => ['app.relationships.organizations*']],
                        ['label' => 'Journalists', 'route' => 'app.relationships.journalists', 'active' => ['app.relationships.journalists']],
                        ['label' => 'Influencers', 'route' => 'app.relationships.influencers', 'active' => ['app.relationships.influencers']],
                        ['label' => 'Experts', 'route' => 'app.relationships.experts', 'active' => ['app.relationships.experts']],
                        ['label' => 'Relationship Graph', 'route' => 'app.relationships', 'active' => ['app.relationships']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Assets',
            'items' => [
                [
                    'key' => 'assets',
                    'label' => 'Assets',
                    'description' => 'Asset library, media, brand assets and generated media.',
                    'route' => 'app.assets.index',
                    'active' => ['app.assets*'],
                    'modules' => ['content'],
                    'permission' => 'view_content',
                    'icon' => 'image',
                    'children' => [
                        ['label' => 'Library', 'route' => 'app.assets.index', 'active' => ['app.assets.index']],
                        ['label' => 'Media', 'route' => 'app.assets.media', 'active' => ['app.assets.media']],
                        ['label' => 'Brand Assets', 'route' => 'app.assets.brand', 'active' => ['app.assets.brand']],
                        ['label' => 'Generated Media', 'route' => 'app.assets.generated', 'active' => ['app.assets.generated']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Reporting',
            'items' => [
                [
                    'key' => 'reporting',
                    'label' => 'Reporting',
                    'description' => 'Analytics, reports and executive reporting.',
                    'route' => 'app.reports',
                    'active' => ['app.reporting*', 'app.reports*', 'app.analytics'],
                    'modules' => ['core', 'content'],
                    'permission' => 'view_dashboard',
                    'icon' => 'bar-chart',
                    'children' => [
                        ['label' => 'Analytics', 'route' => 'app.analytics', 'active' => ['app.reporting.analytics', 'app.analytics'], 'modules' => ['content'], 'permission' => 'view_content'],
                        ['label' => 'Reports', 'route' => 'app.reports', 'active' => ['app.reporting.reports*', 'app.reports*']],
                        ['label' => 'Executive Reports', 'route' => 'app.reporting.executive', 'active' => ['app.reporting.executive']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Administration',
            'items' => [
                [
                    'key' => 'administration',
                    'label' => 'Administration',
                    'description' => 'Account, brands, team, integrations, billing and settings.',
                    'route' => 'settings.account',
                    'active' => ['settings.*', 'app.admin.*', 'app.domain-events'],
                    'modules' => ['core'],
                    'permission' => 'manage_account',
                    'icon' => 'settings',
                    'children' => [
                        ['label' => 'Brands', 'route' => 'settings.brands', 'active' => ['settings.brands']],
                        ['label' => 'Team', 'route' => 'settings.team', 'active' => ['settings.team'], 'permission' => 'manage_users'],
                        ['label' => 'Integrations', 'route' => 'settings.integrations', 'active' => ['settings.integrations*']],
                        ['label' => 'Connectors', 'route' => 'settings.connectors', 'active' => ['settings.connectors'], 'modules' => ['connectors']],
                        ['label' => 'Billing', 'route' => 'settings.modules', 'active' => ['settings.modules'], 'permission' => 'manage_billing'],
                        ['label' => 'Credits', 'route' => 'app.admin.credits', 'active' => ['app.admin.credits']],
                        ['label' => 'Settings', 'route' => 'settings.account', 'active' => ['settings.account']],
                        ['label' => 'Developer Tools', 'route' => 'app.admin.developer-tools', 'active' => ['app.admin.developer-tools*', 'app.domain-events'], 'permission' => 'manage_account'],
                    ],
                ],
            ],
        ],
    ],
];
